<?php
use Application\Utilities\Misc;
$allInstitutes = $this->allInstitutes;
$countries = Misc::getCountries();
?><div class="row">
	<div class="adMnIdL col-lg-9 col-xs-9 col-md-9 col-sm-9">
		<div class="row">
			<h2>
				Institute List<a
					href="<?php echo $this->url('institute/register'); ?>"><i
					class="fa fa-plus-circle"></i></a>
			</h2>
		
		<?php
if (empty($allInstitutes)) {
    ?><h2>No Institues have been Registered so far</h2>
			<a href="<?php echo $this->url('institute/register'); ?>">Click here
				to add institute <i class="fa fa-plus-circle"></i>
			</a>
		
   <?php
} else {
    ?>
		<div class="col-lg-12">
				<input type="search" class="form-control" id="input-search"
					placeholder="Search Institutes">
			</div>
			<div class="searchable-container">
			<?php
    foreach ($allInstitutes as $institute) {
        $status = $institute['enabled'];
        if ($status == 0) {
            $class = "alert-danger";
            $status = 'DISABLED';
        } else {
            $status = 'ENABLED';
            $class = "alert-success";
        }
        ?>
			<div class="items col-xs-12 col-sm-12 col-md-12 col-lg-12 clearfix">
					<div class="info-block block-info clearfix">
						<h5>
							<i class="fa fa-university"></i>
					<?php echo ucwords($institute['name']);?> <a
								href="<?php echo $this->url('institute/update',array('instituteId'=>$institute['id'])); ?>"><i
								class="fa fa-pencil-square-o"></i> </a>
						</h5>
						<h6>
							<i class="fa fa-envelope-o"></i>  <?php echo $institute['emailId'];?>
						<?php
        if (! empty($institute['emailIdTwo'])) {
            ?>
						   <br> <i class="fa fa-envelope-o"></i>  <?php echo $institute['emailIdTwo'];?>
						   <?php
        }
        ?>
					</h6>
						<p>
							<i class="fa fa-location-arrow"></i>
					Location: <?php echo $countries[$institute['country']];?>,<?php echo $institute['pincode'];?></p>
					
		<?php
        if (! empty($institute['phoneNumber'])) {
            ?>
             <span> <i class="fa fa-phone"></i>
             <?php echo $institute['phoneNumber'];?>
             </span>
             <?php
        }
        ?>
        <?php
        if (! empty($institute['phoneNumberTwo'])) {
            ?>
             <span> <i class="fa fa-phone"></i>
             <?php echo $institute['phoneNumberTwo'];?>
             </span>
             <?php
        }
        ?>
        <?php
        if (! empty($institute['phoneNumberThree'])) {
            ?>
             <span> <i class="fa fa-phone"></i>
             <?php echo $institute['phoneNumberThree'];?>
             </span>
             <?php
        }
        ?>
					<h5>
							<a class="btn btn-xs btn-default"
								href="<?php echo $this->url('programme/register', array('instituteId'=>$institute['id'])); ?>">Add
								Programme&nbsp;<i class="fa fa-plus-square-o"></i>
							</a>&nbsp;&nbsp;&nbsp;<a class="btn btn-xs btn-default"
								href="<?php echo $this->url('programme/list', array('instituteId'=>$institute['id'])); ?>">
								View Programmes&nbsp;<i class="fa fa-th-list"></i>
							</a> &nbsp;&nbsp;&nbsp;<a class="btn btn-xs btn-default"
								href="/agent/register/<?php echo $institute['id']?>"> Add
								Agent&nbsp;<i class="fa fa-plus"></i>
							</a> &nbsp;&nbsp;&nbsp;<a class="btn btn-xs btn-default"
								href="/student/list?search=<?php echo urlencode($institute['name'])?>"> View
								Students&nbsp;<i class="fa fa-th-list"></i>
							</a>
						</h5>

					</div>
				</div>
			<?php
    }
    ?>
		</div>
		<?php
}
/*echo "<pre>";
print_r(get_included_files());
echo "</pre>";*/
?>
	</div>
	</div>
</div>
<style>
.glyphicon-lg {
	font-size: 4em
}

.info-block {
	border-right: 5px solid #E6E6E6;
	border-bottom: 1px solid #E6E6E6;
	margin-bottom: 25px
}

.info-block .square-box {
	width: 100px;
	min-height: 110px;
	margin-right: 22px;
	text-align: center !important;
	background-color: #676767;
	padding: 20px 0
}

.info-block.block-info {
	border-color: #20819e
}

.info-block.block-info .square-box {
	background-color: #20819e;
	color: #FFF
}
</style>
<script type="text/javascript">
$(function() {    
    $('#input-search').on('keyup', function() {
      var rex = new RegExp($(this).val(), 'i');
        $('.searchable-container .items').hide();
        $('.searchable-container .items').filter(function() {
            return rex.test($(this).text());
        }).show();
    });
});
</script>
