<div class="row">
	
	<div class="adMnIdL col-lg-12 col-xs-12 col-md-12 col-sm-12">
	<?php
$instituteComponents = $this->instituteComponents;
$institutesInfo = $this->institutesInfo;
if (empty($instituteComponents)) {
    ?>
	    <h3>No Fee Structure(s) exist</h3>
	    <?php
} else {
    
    foreach ($instituteComponents as $instituteId => $components) {
        
        ?>
       <table class="table table-bordered">
			<caption>Fee Structure for: 
                             
                             <?php echo $institutesInfo[$instituteId]['name']?> <a
					href="<?php echo $this->url('institute/updatefeestructure',array('instituteId'=>$instituteId)); ?>"><i
					class="fa fa-pencil-square-o"></i> </a>
			</caption>
			<thead>
				<tr class="table_border">
					<?php
        foreach ($components as $component) {
            $status = $component['enabled'];
            if ($status == 0) {
                $class = "text-danger";
                $status = 'DISABLED';
            } else {
                $status = 'ENABLED';
                $class = "text-success";
            }
            ?>
					    <td class="<?php echo $class?>"><?php echo $component['name'].'('.$status.')'?></td>
					    <?php
        }
        ?>
				</tr>
			</thead>
			<tbody><?php
        foreach ($components as $component) {
            
            ?>
					    <td><?php echo $component['amount']?></td>
					    <?php
        }
        ?>
		
		</tbody>

		</table>
       <?php
    }
    ?><?php
}
?></div>
</div>
