<?php
use Application\Utilities\Misc;
$allInstitutes = $this->allInstitutes;
$countries = Misc::getCountries();
?>
<div class="row">
	<section class="content">
		<div class="row">
		<?php
			if (empty($allInstitutes)) {
			?>
				<h2>No Institues have been Registered so far</h2>
				<a href="<?php echo $this->url('institute/register'); ?>">Click here
				to add institute <i class="fa fa-plus-circle"></i>
				</a>
		
		<?php
			}     
			else {
			?>
				<div class="col-lg-12">
					<input type="search" class="form-control" id="input-search" placeholder="Search Institutes">
				</div>
				<div class="searchable-container">
				<?php
				    foreach ($allInstitutes as $institute) {
				        $status = $institute['enabled'];
				        if ($status == 0) {
				            $class = "alert-danger";
				            $status = 'DISABLED';
				        } else {
				            $status = 'ENABLED';
				            $class = "alert-success";
        				}
			        ?>
					<div class="col-md-3">
				              <!-- Profile Image -->
						<div class="box box-primary">
							<div class="box-body box-profile">
								<img alt="User profile picture" src="/css/dist/img/user4-128x128.jpg" class="profile-user-img img-responsive img-circle">
								<h3 class="profile-username text-center"><?php echo ucwords($institute['name']);?>
 <a href="<?php echo $this->url('institute/update',array('instituteId'=>$institute['id'])); ?>"></h3>
                 						 <p class="text-muted text-center"><?php echo $institute['emailId'];?>
								   <br> <i class="fa fa-envelope-o"></i>  <?php echo $institute['emailIdTwo'];?>
								</p>

                  <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                      <b>Followers</b> <a class="pull-right"><?php echo $countries[$institute['country']];?>,<?php echo $institute['pincode'];?></a>
                    </li>
                    <li class="list-group-item">
                      <b>Following</b> <a class="pull-right"><?php echo $institute['phoneNumber'];?></a>
                    </li>
                    <li class="list-group-item">
                      <b>Friends</b> <a class="pull-right"> <?php echo $institute['phoneNumberTwo'];?></a>
                    </li>
 <li class="list-group-item">
                      <b>Friends</b> <a class="pull-right"> <? echo $institute['phoneNumberThree'];?></a>
                    </li>
                  </ul>

                  <a class="btn btn-primary btn-block" href="#"><b>Follow</b></a>

                </div><!-- /.box-body -->
              </div>
</div>
</div>

<?php
}

}
/*echo "<pre>";
print_r(get_included_files());
echo "</pre>";*/
?>





	</div>
	</div>
</div>

</style>
<script type="text/javascript">
$(function() {    
    $('#input-search').on('keyup', function() {
      var rex = new RegExp($(this).val(), 'i');
        $('.searchable-container .items').hide();
        $('.searchable-container .items').filter(function() {
            return rex.test($(this).text());
        }).show();
    });
});
</script>
