<div class="row">
	
	<div class="adMnIdL col-lg-12 col-xs-12 col-md-12 col-sm-12">
	<?php
$instInfo = $this->instInfo;
?>
		<h3 class="text-center">
			Fee Structure for <?php echo $instInfo['name']?><sup>
<!--a href="/institute/listcomponents"> <i class="fa fa-list-alt"></i>
			</a--></sup>
		</h3>
		<div class="row" id="userRegForm">
			<div
				class="col-md-offset-2 col-xs-offset-2 col-sm-offset-2 col-md-7 col-sm-7 col-xs-7">
		

<?php
$allFields = $this->allFields;
$form = $this->form;
$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form');
$form->setAttribute('role', 'form');
$form->setAttribute('autocomplete', 'off');
echo $this->form()->openTag($form);
?>

<?php
foreach ($allFields as $key) {
    echo '<div class="well well-sm">';
    $amt = $key . 'amount';
    $act = $key . 'action';
    
    $keyE = $form->get($key);
    echo $this->formtext($keyE);
    echo $this->formelementerrors($keyE);
    
    $acte = $form->get($act);
    echo $this->formselect($acte);
    
    $amte = $form->get($amt);
    echo $this->forminput($amte);
    echo $this->formelementerrors($amte);
    echo "</div>";
}

$csrf = $form->get('mcsrf');
echo $this->formhidden($csrf);
echo $this->formElementErrors($csrf);

?>
		

		<div class="form-group">
					<div class="control-group">
						<div class="controls">
							<button class="btn btn-primary btn-block">Save</button>
						</div>
					</div>
				</div>
		<?php
echo $this->form()->closeTag();
?>
		</div>

		</div>
	</div>
</div>

