<div class="row" id="userRegForm">
	<div
		class="well col-md-offset-3 col-xs-offset-3 col-sm-offset-3 col-md-6 col-sm-6 col-xs-6">
		<h5 class="login-box-msg text-center">User Registration</h5>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form');
$form->setAttribute('role', 'form');
$form->setAttribute('autocomplete', 'off');
echo $this->form()->openTag($form);
?>
<div class="form-group col-md-6 col-sm-6 col-xs-12">
<?php

$fullName = $form->get('fullName');
echo $this->formtext($fullName);
echo $this->formelementerrors($fullName);
?>
</div>
<div class="form-group col-md-6 col-sm-6 col-xs-12">
<?php

$loginId = $form->get('loginId');
echo $this->formtext($loginId);
echo $this->formelementerrors($loginId);
?></div><div class="form-group col-md-6 col-sm-6 col-xs-12">
						<?php
    $password = $form->get('password');
    echo $this->formpassword($password);
    echo $this->formelementerrors($password);
    ?></div>
	<div class="form-group col-md-6 col-sm-6 col-xs-12">					<?php
    $passwordConfirm = $form->get('passwordConfirm');
    echo $this->formpassword($passwordConfirm);
    echo $this->formelementerrors($passwordConfirm);
    ?></div>
<div class="form-group col-md-6 col-sm-6 col-xs-12">
<?php

    $personalEmailId = $form->get('personalEmailId');
    echo $this->formemail($personalEmailId);
    echo $this->formelementerrors($personalEmailId);
    ?>
</div>
<div class="form-group col-md-6 col-sm-6 col-xs-12">
	<?php

$mobile = $form->get('mobile');
echo $this->formnumber($mobile);
echo $this->formelementerrors($mobile);
?></div><br> 
<br> 
<div class="col-md-12 col-sm-12 col-xs-12">
Birthday On:
		<div class="row">

			<div class="form-group column col-md-3 col-sm-3 col-xs-3">
			<?php
$birthDay = $form->get('birthDay');
echo $this->formselect($birthDay);

?>
			</div>
			<div class="form-group column col-md-4 col-sm-4 col-xs-4"><?php

$birthMonth = $form->get('birthMonth');
echo $this->formselect($birthMonth);
?>
			</div>
			<div class="form-group column col-md-5 col-sm-5 col-xs-5"><?php

$birthYear = $form->get('birthYear');
echo $this->forminput($birthYear);
?>
			</div>
			<?php echo $this->formElementErrors($birthDay);?>
			<?php echo $this->formElementErrors($birthMonth);?>
			<?php echo $this->formElementErrors($birthYear);?>
			
</div></div>
	<?php
$csrf = $form->get('mcsrf');
echo $this->formhidden($csrf);
echo $this->formElementErrors($csrf);

?>
<div class="form-group col-md-12 col-sm-12 col-xs-12">
<?php

$gender = $form->get('gender');
echo $this->formselect($gender);
echo $this->formelementerrors($gender);
?></div>
	<?php
/*
 * $marritalStatus = $form->get('marritalStatus');
 * echo $this->formselect($marritalStatus);
 * echo $this->formelementerrors($marritalStatus);
 */
?>		
		

<?php
/*
 * echo 'Address:';
 * $nationality = $form->get('nationality');
 * echo $this->formselect($nationality);
 * echo $this->formelementerrors($nationality);
 * ?>
 * <?php
 *
 * $state = $form->get('state');
 * echo $this->formselect($state);
 * echo $this->formelementerrors($state);
 * ?>
 * <?php
 *
 * $city = $form->get('city');
 * echo $this->forminput($city);
 * echo $this->formelementerrors($city);
 * ?>
 * <?php
 *
 * $district = $form->get('district');
 * echo $this->forminput($district);
 * echo $this->formelementerrors($district);
 * ?>
 * <?php
 *
 * $pincode = $form->get('pincode');
 * echo $this->forminput($pincode);
 * echo $this->formelementerrors($pincode);
 */
?>


		<div class="form-group col-md-12 col-sm-12 col-xs-12">
                    <div class="form-group">
			<div class="control-group">
				<div class="controls">
					<button class="btn btn-primary btn-block btn-flat">Save</button>
				</div></div>
			</div>
		</div>
		<?php
echo $this->form()->closeTag();
?>
		</div>

</div>
