<?php
//$institute = $this->institute;
?>
<div class="row">
	<div class="adMnIdL col-lg-offset-2 col-md-offset-2 col-sm-offset-2 col-xs-offset-0 col-lg-8 col-xs-12 col-md-8 col-sm-8">



<div class="box box-primary clearfix">
                
               <div class="" id="userRegForm">

			<div class="col-md-12 col-sm-12 col-xs-12">
				
				<h3 class="text-center">
					Agent Management<!--<a
						href="<?php echo $this->url('agent/list',array('instituteId'=>$institute['id'])); ?>">
						<i class="fa fa-list-alt"></i>
					</a>-->
				</h3>
                                    <?php //print_r($institute);?>
				<h5 class="text-center">
					<i class="fa fa-university"></i>
	                         (<?php echo ucwords($institute['name'])?>)
                     <p>E-mail:(<?php echo ucwords($institute['emailId'])?>)</br>
                          Phone:(<?php echo ucwords($institute['phoneNumber'])?>)</br>
                          Country:(<?php echo ucwords($institute['country'])?>)</br>
                         Pin Code:(<?php echo ucwords($institute['pincode'])?>)</p>

	</h5>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form');
$form->setAttribute('role', 'form');
$form->setAttribute('autocomplete', 'off');
echo $this->form()->openTag($form);
?>
<div class="fform-group col-md-6 col-sm-6 col-xs-12">
                      <label for="exampleInputEmail1">Name</label>
                      <?php

$name = $form->get('name');
echo $this->forminput($name);
echo $this->formelementerrors($name);
?></div>

<div class="form-group col-md-6 col-sm-6 col-xs-12">
                      <label for="exampleInputEmail1">Commission</label>
<?php

$commission = $form->get('commissionPercentage');
echo $this->formnumber($commission);
echo $this->formelementerrors($commission);
?>
</div>
<div class="form-group col-md-6 col-sm-6 col-xs-12">
                      <label for="exampleInputEmail1">E-mail Id</label>
<?php

$emailId = $form->get('emailId');
echo $this->formemail($emailId);
echo $this->formelementerrors($emailId);
?>
</div>
<div class="form-group col-md-6 col-sm-6 col-xs-12">
                      <label for="exampleInputEmail1">Mobile</label>
<?php

$mobile = $form->get('mobile');
echo $this->formnumber($mobile);
echo $this->formelementerrors($mobile);
?>
</div>
<div class="form-group col-md-6 col-sm-6 col-xs-12">
                      <label for="exampleInputEmail1">Status</label>
<?php

$status = $form->get('enabled');
echo $this->formselect($status);

?>
</div>
<div class="form-group col-md-6 col-sm-6 col-xs-12">
                      <label for="exampleInputEmail1">Agent Address</label>
<?php

$address = $form->get('address');
echo $this->formtextarea($address);
echo $this->formelementerrors($address);
?>
</div>

<?php

$csrf = $form->get('mcsrf');
echo $this->formhidden($csrf);
echo $this->formElementErrors($csrf);

?>


		<div class="form-group">
					<div class="control-group">
						<div class="controls">
							<button class="btn btn-primary btn-block">Save</button>
						</div>
					</div>
				</div>
<?php
echo $this->form()->closeTag();
?>

	
	</div>
              </div>


		
	</div>
</div></div>
<style>
div.yup123 label {
	display: block;
}
</style>
