<?php
echo $this->headLink()->prependStylesheet($this->basePath('css/indexIndex.min.css'));
echo $this->headScript()->prependFile($this->basePath('js/indexIndex.min.js'));
?>
<!DOCTYPE html>
<html lang="en">

<head>

<meta charset="utf-8">
<?php

echo $this->headTitle($this->translate('Commission Management '))
    ->setSeparator(' - ')
    ->setAutoEscape(false)?>
        <?php
        echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        echo $this->headLink()
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/indexIndexBoot.min.css'));
        echo $this->headLink()->prependStylesheet(
            $this->basePath() . '/fontawesome/css/font-awesome.css');
        ?>
</head>

<body>
<div class="container">
		<div class="row">

			<!-- LOGO -->
			<div class="col-xs-12 col-sm-6 logo">
				<div class="logo-image">
					<a href="/" title="The Imperial College of Australia"> <img
						class="logo-img" src="<?php echo $this->basePath('images/logo.png')?>"
						alt="The Imperial College of Australia" /> <span>The Imperial
							College of Australia</span>
					</a> <small class="site-slogan">striving for excellence</small>
				</div>
			</div>
			<!-- //LOGO -->

			<div class="col-xs-12 col-sm-6">
				<!-- HEAD SEARCH -->
				<div class="head-search ">


					<div class="custom">
						<div style="text-align: right;">
							<span style="color: #000080;"><span style="font-size: 12pt;"><strong><span
										style="font-size: 20pt;">The Imperial College of Australia</span></strong></span><br />
							<span style="font-size: 10pt;">212 Hoddle Street, Abbotsford</span></span><span
								style="font-size: 10pt;">, <span style="color: #000080;">Victoria
									3067. Australia <br />CRICOS: 02858M, RTO: 121966<br /> Phone:
									61 3 9417 4777 (<a href="/telemarketing-scam-warning"
									title="Telemarketing Scam Warning">Telemarketing Scam Warning</a>),
									Fax: 61 3 9417 4787
							</span></span>
						</div>
					</div>

				</div>
				<!-- //HEAD SEARCH -->



			</div>
		</div>
	</div>
	
	<!-- Navigation -->
	<nav class="navbar navbar-amrit navbar-custom navbar-fixed-top">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header page-scroll">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="frtyui navbar-brand" href="/"><i class="fa fa-home"></i>
					Imperial College</a>
			</div>

			<?php
if (! $this->identity()) {
    ?>
			<div class="collapse navbar-collapse"
				id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<li class="frtyui"><a href="/anonymous/signup">Sign Up</a></li>
					<li class="frtyui"><a href="/anonymous/signin">Sign In</a></li>
				</ul>
			</div>
			<?php
}
?>
			<!-- /.navbar-collapse -->
		</div>
		<!-- /.container -->
	</nav>

	<!-- Page Header -->
	<!-- Set your background image for this header on the line below. -->
	<header class="intro-header"
		style="background-image: url('<?php echo $this->basePath('images/1_960_330.jpg')?>')">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
					<div class="site-heading">
						<h1 class="frtyui">Welcome</h1>
						<hr class="small">
						<span class="subheading frtyui">The Imperial College of Australia</span>
					</div>
				</div>
			</div>
		</div>
	</header>
	<h1 class="text-center">Commission Management</h1>

 <?php
echo $this->headScript()
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery.min.js'))
    ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', 
    array(
        'conditional' => 'lt IE 9'
    ))
    ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', 
    array(
        'conditional' => 'lt IE 9'
    ));

?>
<?php

echo $this->headScript()->prependFile($this->basePath('js/indexIndex.min.js'));
echo $this->headLink()->prependStylesheet($this->basePath('css/indexIndex.min.css'));
?>
	<style>
span.frtyui {
	color: black;
}

li.frtyui {
	color: black;
}

a.frtyui {
	color: black;
}

h1.frtyui {
	color: black;
}
nav.navbar-amrit{
	background-color: rgb(28, 31, 115);
	margin-top: 120px;
}

</style>
<script type="text/javascript">

</script>
</body>

</html>